using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace BursaryTracer.Data.Migrations
{
    public partial class Initials : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "SchoolCategories",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SchoolCategories", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "States",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    StateCode = table.Column<string>(nullable: true),
                    Name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_States", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Cities",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    StateId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Cities", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Cities_States_StateId",
                        column: x => x.StateId,
                        principalTable: "States",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Governors",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    StartsTenure = table.Column<string>(nullable: true),
                    EndsTenure = table.Column<string>(nullable: true),
                    StateId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Governors", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Governors_States_StateId",
                        column: x => x.StateId,
                        principalTable: "States",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Schools",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    Abbreviation = table.Column<string>(nullable: true),
                    StateId = table.Column<int>(nullable: false),
                    SchoolCategoryId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Schools", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Schools_SchoolCategories_SchoolCategoryId",
                        column: x => x.SchoolCategoryId,
                        principalTable: "SchoolCategories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Schools_States_StateId",
                        column: x => x.StateId,
                        principalTable: "States",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Faculties",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    CourseId = table.Column<int>(nullable: false),
                    SchoolId = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Faculties", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Faculties_Schools_SchoolId",
                        column: x => x.SchoolId,
                        principalTable: "Schools",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Courses",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    FacultyId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Courses", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Courses_Faculties_FacultyId",
                        column: x => x.FacultyId,
                        principalTable: "Faculties",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Students",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    FirstName = table.Column<string>(nullable: true),
                    MiddleName = table.Column<string>(nullable: true),
                    Surname = table.Column<string>(nullable: true),
                    StateId = table.Column<int>(nullable: false),
                    CourseId = table.Column<int>(nullable: false),
                    Amount = table.Column<double>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Students", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Students_Courses_CourseId",
                        column: x => x.CourseId,
                        principalTable: "Courses",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Students_States_StateId",
                        column: x => x.StateId,
                        principalTable: "States",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Faculties",
                columns: new[] { "Id", "CourseId", "Name", "SchoolId" },
                values: new object[,]
                {
                    { 1, 0, "Faculty of Agriculture", null },
                    { 12, 0, "Faculty of Pharmaceutical Sciences", null },
                    { 10, 0, "Faculty of Veterinary Medicine", null },
                    { 9, 0, "Faculty of Law", null },
                    { 8, 0, "Faculty of Science and Technology", null },
                    { 7, 0, "Faculty of Engineering", null },
                    { 11, 0, "Faculty of Biological Sciences", null },
                    { 5, 0, "Faculty of Education", null },
                    { 4, 0, "Faculty of Business Administration", null },
                    { 3, 0, "Faculty of Medical Sciences", null },
                    { 2, 0, "Faculty of Arts", null },
                    { 6, 0, "Faculty of Social Sciences", null }
                });

            migrationBuilder.InsertData(
                table: "SchoolCategories",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "College" },
                    { 2, "Polytechnic" },
                    { 3, "University" }
                });

            migrationBuilder.InsertData(
                table: "States",
                columns: new[] { "Id", "Name", "StateCode" },
                values: new object[,]
                {
                    { 26, "Niger", "NI" },
                    { 21, "Kebbi", "KE" },
                    { 22, "Kogi", "KO" },
                    { 23, "Kwara", "KW" },
                    { 24, "Lagos", "LA" },
                    { 25, "Nasarawa", "NA" },
                    { 27, "Ogun", "OG" },
                    { 35, "Yobe", "YO" },
                    { 29, "Osun", "OS" },
                    { 30, "Oyo", "OY" },
                    { 31, "Plateau", "PL" },
                    { 32, "Rivers", "RI" },
                    { 33, "Sokoto", "SO" },
                    { 34, "Taraba", "TA" },
                    { 20, "Katsina", "KT" },
                    { 28, "Ondo", "ON" },
                    { 19, "Kano", "KN" },
                    { 11, "Ebonyi", "EB" },
                    { 17, "Jigawa", "JI" },
                    { 1, "Abia", "AB" },
                    { 2, "Adamawa", "AD" },
                    { 3, "Akwa Ibom", "AK" },
                    { 4, "Anambra", "AN" },
                    { 5, "Bauchi", "BA" },
                    { 6, "Bayelsa", "BY" },
                    { 7, "Benue", "BE" },
                    { 18, "Kaduna", "KD" },
                    { 8, "Borno", "BO" },
                    { 10, "Delta", "DE" },
                    { 36, "Zamfara", "ZA" },
                    { 12, "Edo", "ED" },
                    { 13, "Ekiti", "EK" },
                    { 14, "Enugu", "EN" },
                    { 15, "Gombe", "GO" },
                    { 16, "Imo", "IM" },
                    { 9, "Cross River", "CR" },
                    { 37, "FCT", "FC" }
                });

            migrationBuilder.InsertData(
                table: "Cities",
                columns: new[] { "Id", "Name", "StateId" },
                values: new object[,]
                {
                    { 1904, "Bebeji", 19 },
                    { 1703, "Biriniwa", 17 },
                    { 1704, "Birnin Kudu", 17 },
                    { 1705, "Buji", 17 },
                    { 1706, "Dutse", 17 },
                    { 1707, "Gagarawa", 17 },
                    { 1708, "Garki", 17 },
                    { 1709, "Gumel", 17 },
                    { 1710, "Guri", 17 },
                    { 1711, "Gwaram", 17 },
                    { 1702, "Babura", 17 },
                    { 1712, "Gwiwa", 17 },
                    { 1714, "Jahun", 17 },
                    { 1715, "Kafin Hausa", 17 },
                    { 1716, "Kaugama", 17 },
                    { 1717, "Kazaure", 17 },
                    { 1718, "Kiri Kasama", 17 },
                    { 1719, "Kiyawa", 17 },
                    { 1720, "Maigatari", 17 },
                    { 1721, "Malam Madori", 17 },
                    { 1722, "Miga", 17 },
                    { 1713, "Hadejia", 17 },
                    { 1701, "Auyo", 17 },
                    { 2807, "Ese Odo", 28 },
                    { 2808, "Idanre", 28 },
                    { 1612, "Ngor Okpala", 16 },
                    { 1613, "Njaba", 16 },
                    { 1614, "Nkwerre", 16 },
                    { 1615, "Nwangele", 16 },
                    { 1616, "Obowo", 16 },
                    { 1617, "Oguta", 16 },
                    { 1618, "Ohaji | Egbema", 16 },
                    { 1619, "Okigwe", 16 },
                    { 1620, "Onuimo", 16 },
                    { 1621, "Orlu", 16 },
                    { 1622, "Orsu", 16 },
                    { 1623, "Oru East", 16 },
                    { 1624, "Oru West", 16 },
                    { 1625, "Owerri Municipal", 16 },
                    { 1626, "Owerri North", 16 },
                    { 1627, "Owerri West", 16 },
                    { 2813, "Odigbo", 28 },
                    { 2812, "Irele", 28 },
                    { 2811, "Ile Oluji | Okeigbo", 28 },
                    { 2810, "Ilaje", 28 },
                    { 2809, "Ifedore", 28 },
                    { 1723, "Ringim", 17 },
                    { 1611, "Mbaitoli", 16 },
                    { 1724, "Roni", 17 },
                    { 1726, "Taura", 17 },
                    { 1820, "Sanga", 18 },
                    { 1821, "Soba", 18 },
                    { 1822, "Zangon Kataf", 18 },
                    { 1823, "Zaria", 18 },
                    { 2801, "Akoko North-East", 28 },
                    { 2720, "Yewa South (Egbado);", 27 },
                    { 2719, "Yewa North (Egbado);", 27 },
                    { 2718, "Sagamu", 27 },
                    { 2717, "Remo North", 27 },
                    { 1819, "Sabon-Gari", 18 },
                    { 2716, "Ogun Waterside", 27 },
                    { 2714, "Odeda", 27 },
                    { 2713, "Obafemi-Owode", 27 },
                    { 2712, "Ipokia", 27 },
                    { 2711, "Imeko-Afon", 27 },
                    { 2710, "Ikenne", 27 },
                    { 2709, "Ijebu-Ode", 27 },
                    { 2708, "Ijebu North-East", 27 },
                    { 2707, "Ijebu North", 27 },
                    { 1901, "Ajingi", 19 },
                    { 2715, "Odogbolu", 27 },
                    { 1818, "Makarfi", 18 },
                    { 1817, "Lere", 18 },
                    { 1816, "Kudan", 18 },
                    { 1727, "Yankwashi", 17 },
                    { 2806, "Akure South", 28 },
                    { 2805, "Akure North", 28 },
                    { 2804, "Akoko South-West", 28 },
                    { 2803, "Akoko South-East", 28 },
                    { 2802, "Akoko North-West", 28 },
                    { 1801, "Birnin Gwari", 18 },
                    { 1802, "Chikun", 18 },
                    { 1803, "Giwa", 18 },
                    { 1804, "Igabi", 18 },
                    { 1805, "Ikara", 18 },
                    { 1806, "Jaba", 18 },
                    { 1807, "Jema a", 18 },
                    { 1808, "Kachia", 18 },
                    { 1809, "Kaduna North", 18 },
                    { 1810, "Kaduna South", 18 },
                    { 1811, "Kagarko", 18 },
                    { 1812, "Kajuru", 18 },
                    { 1813, "Kaura", 18 },
                    { 1814, "Kauru", 18 },
                    { 1815, "Kubau", 18 },
                    { 1725, "Sule Tankarkar", 17 },
                    { 1902, "Albasu", 19 },
                    { 1610, "Isu", 16 },
                    { 1608, "Ikeduru", 16 },
                    { 2918, "Ilesa East", 29 },
                    { 2917, "Ila", 29 },
                    { 2916, "Ifelodun", 29 },
                    { 2915, "Ifedayo", 29 },
                    { 2914, "Ife South", 29 },
                    { 2913, "Ife North", 29 },
                    { 2912, "Ife East", 29 },
                    { 2911, "Ife Central", 29 },
                    { 2910, "Ejigbo", 29 },
                    { 2919, "Ilesa West", 29 },
                    { 2909, "Egbedore", 29 },
                    { 1401, "Aninri", 14 },
                    { 1402, "Awgu", 14 },
                    { 1403, "Enugu East", 14 },
                    { 1404, "Enugu North", 14 },
                    { 1405, "Enugu South", 14 },
                    { 1406, "Ezeagu", 14 },
                    { 1407, "Igbo Etiti", 14 },
                    { 1408, "Igbo Eze North", 14 },
                    { 1409, "Igbo-Eze South", 14 },
                    { 2908, "Ede South", 29 },
                    { 1316, "Oye", 13 },
                    { 1315, "Moba", 13 },
                    { 1314, "Ise | Orun", 13 },
                    { 2927, "Olorunda", 29 },
                    { 2926, "Ola Oluwa", 29 },
                    { 2925, "Odo Otin", 29 },
                    { 2924, "Obokun", 29 },
                    { 2923, "Iwo", 29 },
                    { 2922, "Isokan", 29 },
                    { 2921, "Irewole", 29 },
                    { 2920, "Irepodun", 29 },
                    { 1301, "Ado-Ekiti", 13 },
                    { 1302, "Aiyekire (Gbonyin);", 13 },
                    { 1303, "Efon", 13 },
                    { 1304, "Ekiti East", 13 },
                    { 1305, "Ekiti South-West", 13 },
                    { 1306, "Ekiti West", 13 },
                    { 1307, "Emure", 13 },
                    { 1308, "Ido-Osi", 13 },
                    { 1309, "Ijero", 13 },
                    { 1310, "Ikere", 13 },
                    { 1311, "Ikole", 13 },
                    { 1312, "Ilejemeje", 13 },
                    { 1313, "Irepodun | Ifelodun", 13 },
                    { 1410, "Isi Uzo", 14 },
                    { 1609, "Isiala Mbano", 16 },
                    { 1411, "Nkanu East", 14 },
                    { 1413, "Nsukka", 14 },
                    { 1513, "Kaltungo", 15 },
                    { 1514, "Kaltungo", 15 },
                    { 1515, "Kumo", 15 },
                    { 1516, "Kwami", 15 },
                    { 1517, "Mallam Sidi", 15 },
                    { 1518, "Nafada", 15 },
                    { 1519, "Nafada", 15 },
                    { 1520, "Shongom", 15 },
                    { 1521, "Tallase", 15 },
                    { 1512, "Gombe", 15 },
                    { 1522, "Yamaltu | Deba", 15 },
                    { 2815, "Ondo East", 28 },
                    { 2814, "Okitipupa", 28 },
                    { 1601, "Aboh Mbaise", 16 },
                    { 1602, "Ahiazu Mbaise", 16 },
                    { 1603, "Ehime Mbano", 16 },
                    { 1604, "Ezinihitte Mbaise", 16 },
                    { 1605, "Ideato North", 16 },
                    { 1606, "Ideato South", 16 },
                    { 1607, "Ihitte | Uboma", 16 },
                    { 2816, "Ondo West", 28 },
                    { 1511, "Gombe", 15 },
                    { 1510, "Funakaye", 15 },
                    { 1509, "Dukku", 15 },
                    { 1414, "Oji River", 14 },
                    { 1415, "Udenu", 14 },
                    { 1416, "Udi", 14 },
                    { 1417, "Uzo-Uwani", 14 },
                    { 2907, "Ede North", 29 },
                    { 2906, "Boripe", 29 },
                    { 2905, "Boluwaduro", 29 },
                    { 2904, "Atakunmosa West", 29 },
                    { 2903, "Atakunmosa East", 29 },
                    { 2902, "Aiyedire", 29 },
                    { 2901, "Aiyedaade", 29 },
                    { 2818, "Owo", 28 },
                    { 2817, "Ose", 28 },
                    { 1501, "Akko", 15 },
                    { 1502, "Bajoga", 15 },
                    { 1503, "Balanga", 15 },
                    { 1504, "Billiri", 15 },
                    { 1505, "Billiri", 15 },
                    { 1506, "Boh", 15 },
                    { 1507, "Deba Habe", 15 },
                    { 1508, "Dukku", 15 },
                    { 1412, "Nkanu West", 14 },
                    { 2928, "Oriade", 29 },
                    { 1903, "Bagwai", 19 },
                    { 1905, "Bichi", 19 },
                    { 2208, "Igalamela-Odolu", 22 },
                    { 2209, "Ijumu", 22 },
                    { 2210, "Kabba | Bunu", 22 },
                    { 2211, "Koton Karfe", 22 },
                    { 2212, "Lokoja", 22 },
                    { 2213, "Mopa-Muro", 22 },
                    { 2214, "Ofu", 22 },
                    { 2215, "Ogori | Magongo", 22 },
                    { 2216, "Okehi", 22 },
                    { 2207, "Idah", 22 },
                    { 2217, "Okene", 22 },
                    { 2219, "Omala", 22 },
                    { 2220, "Yagba East", 22 },
                    { 2221, "Yagba West", 22 },
                    { 2608, "Gbako", 26 },
                    { 2607, "Edati", 26 },
                    { 2606, "Chanchaga", 26 },
                    { 2605, "Bosso", 26 },
                    { 2604, "Borgu", 26 },
                    { 2603, "Bida", 26 },
                    { 2218, "Olamaboro", 22 },
                    { 2206, "Ibaji", 22 },
                    { 2205, "Dekina", 22 },
                    { 2204, "Bassa", 22 },
                    { 2112, "Jega", 21 },
                    { 2113, "Kalgo", 21 },
                    { 2114, "Koko | Besse", 21 },
                    { 2115, "Maiyama", 21 },
                    { 2116, "Ngaski", 21 },
                    { 2117, "Sakaba", 21 },
                    { 2118, "Shanga", 21 },
                    { 2119, "Suru", 21 },
                    { 2120, "Yauri", 21 },
                    { 2121, "Zuru", 21 },
                    { 2616, "Mashegu", 26 },
                    { 2615, "Mariga", 26 },
                    { 2614, "Magama", 26 },
                    { 2613, "Lavun", 26 },
                    { 2612, "Lapai", 26 },
                    { 2611, "Kontagora", 26 },
                    { 2610, "Katcha", 26 },
                    { 2609, "Gurara", 26 },
                    { 2201, "Adavi", 22 },
                    { 2202, "Ajaokuta", 22 },
                    { 2203, "Ankpa", 22 },
                    { 2602, "Agwara", 26 },
                    { 2111, "Gwandu", 21 },
                    { 2601, "Agaie", 26 },
                    { 2301, "Asa", 23 },
                    { 2403, "Alimosho", 24 },
                    { 2404, "Amuwo-Odofin", 24 },
                    { 2405, "Apapa", 24 },
                    { 2406, "Badagry", 24 },
                    { 2407, "Epe", 24 },
                    { 2408, "Eti-Osa", 24 },
                    { 2409, "Ibeju-Lekki", 24 },
                    { 2410, "Ifako-Ijaye", 24 },
                    { 2411, "Ikeja", 24 },
                    { 2402, "Ajeromi-Ifelodun", 24 },
                    { 2412, "Ikorodu", 24 },
                    { 2414, "Lagos-Island", 24 },
                    { 2415, "Lagos-Mainland", 24 },
                    { 2416, "Mushin", 24 },
                    { 2417, "Ojo", 24 },
                    { 2418, "Oshodi-Isolo", 24 },
                    { 2419, "Shomolu", 24 },
                    { 2420, "Surulere", 24 },
                    { 2504, "Karu", 25 },
                    { 2503, "Doma", 25 },
                    { 2413, "Kosofe", 24 },
                    { 2401, "Agege", 24 },
                    { 2505, "Keana", 25 },
                    { 2506, "Keffi", 25 },
                    { 2302, "Baruten", 23 },
                    { 2303, "Edu", 23 },
                    { 2304, "Ekiti", 23 },
                    { 2305, "Ifelodun", 23 },
                    { 2306, "Ilorin East", 23 },
                    { 2307, "Ilorin South", 23 },
                    { 2308, "Ilorin West", 23 },
                    { 2309, "Irepodun", 23 },
                    { 2310, "Isin", 23 },
                    { 2311, "Kaiama", 23 },
                    { 2312, "Moro", 23 },
                    { 2313, "Offa", 23 },
                    { 2314, "Oke Ero", 23 },
                    { 2315, "Oyun", 23 },
                    { 2316, "Pategi", 23 },
                    { 2512, "Toto", 25 },
                    { 2511, "Obi", 25 },
                    { 2510, "Nasarawa Egon", 25 },
                    { 2509, "Nasarawa", 25 },
                    { 2508, "Lafia", 25 },
                    { 2507, "Kokona", 25 },
                    { 2513, "Wamba", 25 },
                    { 2706, "Ijebu East", 27 },
                    { 2110, "Fakai", 21 },
                    { 2108, "Dandi", 21 },
                    { 1931, "Nassarawa", 19 },
                    { 1932, "Rano", 19 },
                    { 1933, "Rimin Gado", 19 },
                    { 1934, "Rogo", 19 },
                    { 1935, "Shanono", 19 },
                    { 1936, "Sumaila", 19 },
                    { 1937, "Takai", 19 },
                    { 1938, "Tarauni", 19 },
                    { 1939, "Tofa", 19 },
                    { 1930, "Minjibir", 19 },
                    { 1940, "Tsanyawa", 19 },
                    { 1942, "Ungogo", 19 },
                    { 1943, "Warawa", 19 },
                    { 1944, "Wudil", 19 },
                    { 2705, "Ifo", 27 },
                    { 2704, "Ewekoro", 27 },
                    { 2703, "Ado-Odo | Ota", 27 },
                    { 2702, "Abeokuta South", 27 },
                    { 2701, "Abeokuta North", 27 },
                    { 2625, "Wushishi", 26 },
                    { 1941, "Tudun Wada", 19 },
                    { 1929, "Makoda", 19 },
                    { 1928, "Madobi", 19 },
                    { 1927, "Kura", 19 },
                    { 1906, "Bunkure", 19 },
                    { 1907, "Dala", 19 },
                    { 1908, "Dambatta", 19 },
                    { 1909, "Dawakin Kudu", 19 },
                    { 1910, "Dawakin Tofa", 19 },
                    { 1911, "Doguwa", 19 },
                    { 1912, "Fagge", 19 },
                    { 1913, "Gabasawa", 19 },
                    { 1914, "Garko", 19 },
                    { 1915, "Garun Mallam", 19 },
                    { 1916, "Gaya", 19 },
                    { 1917, "Gezawa", 19 },
                    { 1918, "Gwale", 19 },
                    { 1919, "Gwarzo", 19 },
                    { 1920, "Kabo", 19 },
                    { 1921, "Kano", 19 },
                    { 1922, "Karaye", 19 },
                    { 1923, "Kibiya", 19 },
                    { 1924, "Kiru", 19 },
                    { 1925, "Kumbotso", 19 },
                    { 1926, "Kunchi", 19 },
                    { 2624, "Tafa", 26 },
                    { 2109, "Danko | Wasagu", 21 },
                    { 2623, "Suleja", 26 },
                    { 2002, "Batagarawa", 20 },
                    { 2028, "Matazu", 20 },
                    { 2029, "Musawa", 20 },
                    { 2030, "Rimi", 20 },
                    { 2031, "Sabuwa", 20 },
                    { 2032, "Safana", 20 },
                    { 2033, "Sandamu", 20 },
                    { 2034, "Zango", 20 },
                    { 2622, "Shiroro", 26 },
                    { 2621, "Rijau", 26 },
                    { 2027, "Mashi", 20 },
                    { 2620, "Rafi", 26 },
                    { 2618, "Munya", 26 },
                    { 2617, "Mokwa", 26 },
                    { 2101, "Aleiro", 21 },
                    { 2102, "Arewa Dandi", 21 },
                    { 2103, "Argungu", 21 },
                    { 2104, "Augie", 21 },
                    { 2105, "Bagudo", 21 },
                    { 2106, "Birnin Kebbi", 21 },
                    { 2107, "Bunza", 21 },
                    { 2619, "Paikoro", 26 },
                    { 2026, "Mani", 20 },
                    { 2025, "Malumfashi", 20 },
                    { 2024, "Mai Adua", 20 },
                    { 2003, "Batsari", 20 },
                    { 2004, "Baure", 20 },
                    { 2005, "Bindawa", 20 },
                    { 2006, "Charanchi", 20 },
                    { 2007, "Dan Musa", 20 },
                    { 2008, "Dandume", 20 },
                    { 2009, "Danja", 20 },
                    { 2010, "Daura", 20 },
                    { 2011, "Dutsi", 20 },
                    { 2012, "Dutsin-Ma", 20 },
                    { 2013, "Faskari", 20 },
                    { 2014, "Funtua", 20 },
                    { 2015, "Ingawa", 20 },
                    { 2016, "Jibia", 20 },
                    { 2017, "Kafur", 20 },
                    { 2018, "Kaita", 20 },
                    { 2019, "Kankara", 20 },
                    { 2020, "Kankia", 20 },
                    { 2021, "Katsina", 20 },
                    { 2022, "Kurfi", 20 },
                    { 2023, "Kusada", 20 },
                    { 2001, "Bakori", 20 },
                    { 2929, "Orolu", 29 },
                    { 2930, "Osogbo", 29 },
                    { 1218, "Uhunmwonde", 12 },
                    { 306, "Etim-Ekpo", 3 },
                    { 307, "Etinan", 3 },
                    { 308, "Ibeno", 3 },
                    { 309, "Ibesikpo-Asutan", 3 },
                    { 310, "Ibiono-Ibom", 3 },
                    { 311, "Ika", 3 },
                    { 312, "Ikono", 3 },
                    { 313, "Ikot Abasi", 3 },
                    { 314, "Ikot Ekpene", 3 },
                    { 305, "Essien Udim", 3 },
                    { 315, "Ini", 3 },
                    { 317, "Mbo", 3 },
                    { 318, "Mkpat-Enin", 3 },
                    { 319, "Nsit-Atai", 3 },
                    { 320, "Nsit-Ibom", 3 },
                    { 321, "Nsit-Ubium", 3 },
                    { 322, "Obot-Akara", 3 },
                    { 323, "Okobo", 3 },
                    { 324, "Onna", 3 },
                    { 325, "Oron", 3 },
                    { 316, "Itu", 3 },
                    { 304, "Esit-Eket", 3 },
                    { 303, "Eket", 3 },
                    { 302, "Eastern Obolo", 3 },
                    { 213, "Michika", 2 },
                    { 214, "Mubi North", 2 },
                    { 215, "Mubi South", 2 },
                    { 216, "Numan", 2 },
                    { 217, "Shelleng", 2 },
                    { 218, "Song", 2 },
                    { 219, "Toungo", 2 },
                    { 220, "Yola North", 2 },
                    { 221, "Yola South", 2 },
                    { 3307, "Gwadabawa", 33 },
                    { 3306, "Gudu", 33 },
                    { 3305, "Goronyo", 33 },
                    { 3304, "Gada", 33 },
                    { 3303, "Dange Shuni", 33 },
                    { 3302, "Bodinga", 33 },
                    { 3301, "Binji", 33 },
                    { 3223, "Tai", 32 },
                    { 3222, "Port Harcourt", 32 },
                    { 3221, "Oyigbo", 32 },
                    { 3220, "Opobo�Nkoro", 32 },
                    { 301, "Abak", 3 },
                    { 326, "Oruk Anam", 3 },
                    { 212, "Mayo-Belwa", 2 },
                    { 327, "Ukanafun", 3 },
                    { 329, "Uruan", 3 },
                    { 415, "Nnewi South", 4 },
                    { 416, "Ogbaru", 4 },
                    { 417, "Onitsha North", 4 },
                    { 418, "Onitsha South", 4 },
                    { 419, "Orumba North", 4 },
                    { 420, "Orumba South", 4 },
                    { 421, "Oyi", 4 },
                    { 3210, "Emohua", 32 },
                    { 3209, "Eleme", 32 },
                    { 414, "Nnewi North", 4 },
                    { 3208, "Degema", 32 },
                    { 3206, "Asari-Toru", 32 },
                    { 3205, "Andoni", 32 },
                    { 3204, "Akuku-Toru", 32 },
                    { 3203, "Ahoada West", 32 },
                    { 3202, "Ahoada East", 32 },
                    { 3201, "Abua�Odual", 32 },
                    { 501, "Alkaleri", 5 },
                    { 502, "Bauchi", 5 },
                    { 503, "Bogoro", 5 },
                    { 3207, "Bonny", 32 },
                    { 413, "Njikoka", 4 },
                    { 412, "Ihiala", 4 },
                    { 411, "Idemili South", 4 },
                    { 330, "Urue-Offong | Oruko", 3 },
                    { 331, "Uyo", 3 },
                    { 3219, "Omuma", 32 },
                    { 3218, "Okrika", 32 },
                    { 3217, "Ogu�Bolo", 32 },
                    { 3216, "Ogba�Egbema�Ndoni", 32 },
                    { 3215, "Obio-Akpor", 32 },
                    { 3214, "Khana", 32 },
                    { 3213, "Ikwerre", 32 },
                    { 3212, "Gokana", 32 },
                    { 3211, "Etche", 32 },
                    { 401, "Aguata", 4 },
                    { 402, "Awka North", 4 },
                    { 403, "Awka South", 4 },
                    { 404, "Anambra East", 4 },
                    { 405, "Anambra West", 4 },
                    { 406, "Anaocha", 4 },
                    { 407, "Ayamelum", 4 },
                    { 408, "Dunukofia", 4 },
                    { 409, "Ekwusigo", 4 },
                    { 410, "Idemili North", 4 },
                    { 328, "Udung-Uko", 3 },
                    { 504, "Damban", 5 },
                    { 211, "Maiha", 2 },
                    { 209, "Lamurde", 2 },
                    { 3512, "Nangere", 35 },
                    { 3511, "Machina", 35 },
                    { 3510, "Karasuwa", 35 },
                    { 3509, "Jakusko", 35 },
                    { 3508, "Gulani", 35 },
                    { 3507, "Gujba", 35 },
                    { 3506, "Geidam", 35 },
                    { 3505, "Fune", 35 },
                    { 3504, "Fika", 35 },
                    { 3513, "Nguru", 35 },
                    { 3503, "Damaturu", 35 },
                    { 3501, "Bade", 35 },
                    { 3416, "Zing", 34 },
                    { 3415, "Yorro", 34 },
                    { 3414, "Wukari", 34 },
                    { 3413, "Ussa", 34 },
                    { 3412, "Takum", 34 },
                    { 3411, "Sardauna", 34 },
                    { 3410, "Lau", 34 },
                    { 3409, "Kurmi", 34 },
                    { 3502, "Bursari", 35 },
                    { 3514, "Potiskum", 35 },
                    { 3515, "Tarmuwa", 35 },
                    { 3516, "Yunusari", 35 },
                    { 3706, "Kwali", 37 },
                    { 3705, "Kuje", 37 },
                    { 3704, "Gwagwalada", 37 },
                    { 3703, "Bwari", 37 },
                    { 3702, "Abuja", 37 },
                    { 3701, "Abaji", 37 },
                    { 3614, "Zurmi", 36 },
                    { 3613, "Tsafe", 36 },
                    { 3612, "Talata Mafara", 36 },
                    { 3611, "Shinkafi", 36 },
                    { 3610, "Maru", 36 },
                    { 3609, "Maradun", 36 },
                    { 3608, "Kaura Namoda", 36 },
                    { 3607, "Gusau", 36 },
                    { 3606, "Gummi", 36 },
                    { 3605, "Bungudu", 36 },
                    { 3604, "Bukkuyum", 36 },
                    { 3603, "Birnin Magaji | Kiyaw", 36 },
                    { 3602, "Bakura", 36 },
                    { 3601, "Anka", 36 },
                    { 3517, "Yusufari", 35 },
                    { 3408, "Karim Lamido", 34 },
                    { 210, "Madagali", 2 },
                    { 3407, "Jalingo", 34 },
                    { 3405, "Gassol", 34 },
                    { 112, "Ugwunagbo", 1 },
                    { 113, "Ukwa East", 1 },
                    { 114, "Ukwa West", 1 },
                    { 115, "Umuahia North", 1 },
                    { 116, "Umuahia South", 1 },
                    { 117, "Umu Nneochi", 1 },
                    { 3313, "Sabon Birni", 33 },
                    { 3312, "Rabah", 33 },
                    { 3311, "Kware", 33 },
                    { 111, "Osisioma Ngwa", 1 },
                    { 3310, "Kebbe", 33 },
                    { 3308, "Illela", 33 },
                    { 201, "Demsa", 2 },
                    { 202, "Fufore", 2 },
                    { 203, "Ganye", 2 },
                    { 204, "Girei", 2 },
                    { 205, "Gombi", 2 },
                    { 206, "Guyuk", 2 },
                    { 207, "Hong", 2 },
                    { 208, "Jada", 2 },
                    { 3309, "Isa", 33 },
                    { 110, "Ohafia", 1 },
                    { 109, "Obi Ngwa", 1 },
                    { 108, "Isuikwuato", 1 },
                    { 3404, "Gashaka", 34 },
                    { 3403, "Donga", 34 },
                    { 3402, "Bali", 34 },
                    { 3401, "Ardo Kola", 34 },
                    { 3323, "Yabo", 33 },
                    { 3322, "Wurno", 33 },
                    { 3321, "Wamako", 33 },
                    { 3320, "Tureta", 33 },
                    { 3319, "Tangaza", 33 },
                    { 3318, "Tambuwal", 33 },
                    { 3317, "Sokoto South", 33 },
                    { 3316, "Sokoto North", 33 },
                    { 3315, "Silame", 33 },
                    { 3314, "Shagari", 33 },
                    { 101, "Aba North", 1 },
                    { 102, "Aba South", 1 },
                    { 103, "Arochukwu", 1 },
                    { 104, "Bende", 1 },
                    { 105, "Ikwuano", 1 },
                    { 106, "Isiala Ngwa North", 1 },
                    { 107, "Isiala Ngwa South", 1 },
                    { 3406, "Ibi", 34 },
                    { 505, "Darazo", 5 },
                    { 506, "Dass", 5 },
                    { 507, "Gamawa", 5 },
                    { 1002, "Aniocha South", 10 },
                    { 1003, "Bomadi", 10 },
                    { 1004, "Burutu", 10 },
                    { 1005, "Ethiope East", 10 },
                    { 1006, "Ethiope West", 10 },
                    { 1007, "Ika North East", 10 },
                    { 1008, "Ika South", 10 },
                    { 1009, "Isoko North", 10 },
                    { 1010, "Isoko South", 10 },
                    { 1001, "Aniocha North", 10 },
                    { 1011, "Ndokwa East", 10 },
                    { 1013, "Okpe", 10 },
                    { 1014, "Oshimili North", 10 },
                    { 1015, "Oshimili South", 10 },
                    { 1016, "Patani", 10 },
                    { 1017, "Sapele", 10 },
                    { 1018, "Udu", 10 },
                    { 1019, "Ughelli North", 10 },
                    { 1020, "Ughelli South", 10 },
                    { 1021, "Ukwuani", 10 },
                    { 1012, "Ndokwa West", 10 },
                    { 3016, "Ogbomosho North", 30 },
                    { 3017, "Ogbomosho South", 30 },
                    { 3018, "Oyo West", 30 },
                    { 903, "Akpabuyo", 9 },
                    { 904, "Bekwarra", 9 },
                    { 905, "Biase", 9 },
                    { 906, "Boki", 9 },
                    { 907, "Calabar Municipal", 9 },
                    { 908, "Calabar South", 9 },
                    { 909, "Etung", 9 },
                    { 910, "Ikom", 9 },
                    { 911, "Obanliku", 9 },
                    { 912, "Obubra", 9 },
                    { 913, "Obudu", 9 },
                    { 914, "Odukpani", 9 },
                    { 915, "Ogoja", 9 },
                    { 916, "Yakuur", 9 },
                    { 917, "Yala", 9 },
                    { 3024, "Iwajowa", 30 },
                    { 3023, "Itesiwaju", 30 },
                    { 3022, "Saki East", 30 },
                    { 3021, "Saki West", 30 },
                    { 3020, "Atisbo", 30 },
                    { 3019, "Atiba", 30 },
                    { 1022, "Uvwie", 10 },
                    { 902, "Akamkpa", 9 },
                    { 1023, "Warri North", 10 },
                    { 1025, "Warri South West", 10 },
                    { 3003, "Egbeda", 30 },
                    { 3002, "Akinyele", 30 },
                    { 3001, "Afijio", 30 },
                    { 1201, "Akoko-Edo", 12 },
                    { 1202, "Egor", 12 },
                    { 1203, "Esan Central", 12 },
                    { 1204, "Esan North-East", 12 },
                    { 1205, "Esan South-East", 12 },
                    { 1206, "Esan West", 12 },
                    { 3004, "Ibadan North", 30 },
                    { 1207, "Etsako Central", 12 },
                    { 1209, "Etsako West", 12 },
                    { 1210, "Igueben", 12 },
                    { 1211, "Ikpoba-Okha", 12 },
                    { 1212, "Oredo", 12 },
                    { 1213, "Orhionmwon", 12 },
                    { 1214, "Ovia North-East", 12 },
                    { 1215, "Ovia South-West", 12 },
                    { 1216, "Owan East", 12 },
                    { 1217, "Owan West", 12 },
                    { 1208, "Etsako East", 12 },
                    { 3005, "Ibadan North-East", 30 },
                    { 3006, "Ibadan North-West", 30 },
                    { 3007, "Ibadan South-West", 30 },
                    { 3015, "Lagelu", 30 },
                    { 3014, "Kajola", 30 },
                    { 3013, "Iseyin", 30 },
                    { 3012, "Irepo", 30 },
                    { 3011, "Ido", 30 },
                    { 3010, "Ibarapa East Eruwa", 30 },
                    { 3009, "Ibarapa Central", 30 },
                    { 1101, "Abakaliki", 11 },
                    { 1102, "Afikpo North", 11 },
                    { 1103, "Afikpo South (Edda);", 11 },
                    { 1104, "Ebonyi", 11 },
                    { 1105, "Ezza North", 11 },
                    { 1106, "Ezza South", 11 },
                    { 1107, "Ikwo", 11 },
                    { 1108, "Ishielu", 11 },
                    { 1109, "Ivo", 11 },
                    { 1110, "Izzi", 11 },
                    { 1111, "Ohaozara", 11 },
                    { 1112, "Ohaukwu", 11 },
                    { 1113, "Onicha", 11 },
                    { 3008, "Ibadan South-East", 30 },
                    { 1024, "Warri South", 10 },
                    { 901, "Abi", 9 },
                    { 3025, "Ibarapa North", 30 },
                    { 3026, "Olorunsogo", 30 },
                    { 607, "Southern Ijaw", 6 },
                    { 608, "Yenagoa", 6 },
                    { 3111, "Mangu", 31 },
                    { 3110, "Langtang South", 31 },
                    { 3109, "Langtang North", 31 },
                    { 3108, "Kanke", 31 },
                    { 3107, "Kanam", 31 },
                    { 3106, "Jos South", 31 },
                    { 3105, "Jos North", 31 },
                    { 606, "Sagbama", 6 },
                    { 3104, "Jos East", 31 },
                    { 701, "Ado", 7 }
                });

            migrationBuilder.InsertData(
                table: "Cities",
                columns: new[] { "Id", "Name", "StateId" },
                values: new object[,]
                {
                    { 702, "Agatu", 7 },
                    { 703, "Apa", 7 },
                    { 704, "Buruku", 7 },
                    { 705, "Gboko", 7 },
                    { 706, "Guma", 7 },
                    { 707, "Gwer East", 7 },
                    { 708, "Gwer West", 7 },
                    { 709, "Katsina-Ala", 7 },
                    { 3103, "Bokkos", 31 },
                    { 605, "Ogbia", 6 },
                    { 604, "Nembe", 6 },
                    { 603, "Kolokuma | Opokuma", 6 },
                    { 508, "Ganjuwa", 5 },
                    { 509, "Giade", 5 },
                    { 510, "Itas | Gadau", 5 },
                    { 511, "Jama are", 5 },
                    { 512, "Katagum", 5 },
                    { 513, "Kirfi", 5 },
                    { 514, "Misau", 5 },
                    { 515, "Ningi", 5 },
                    { 516, "Shira", 5 },
                    { 517, "Tafawa Balewa", 5 },
                    { 518, "Toro", 5 },
                    { 519, "Warji", 5 },
                    { 520, "Zaki", 5 },
                    { 3117, "Wase", 31 },
                    { 3116, "Shendam", 31 },
                    { 3115, "Riyom", 31 },
                    { 3114, "Qua an Pan", 31 },
                    { 3113, "Pankshin", 31 },
                    { 3112, "Mikang", 31 },
                    { 601, "Brass", 6 },
                    { 602, "Ekeremor", 6 },
                    { 710, "Konshisha", 7 },
                    { 711, "Kwande", 7 },
                    { 712, "Logo", 7 },
                    { 713, "Makurdi", 7 },
                    { 810, "Guzamala", 8 },
                    { 811, "Gwoza", 8 },
                    { 812, "Hawul", 8 },
                    { 813, "Jere", 8 },
                    { 814, "Kaga", 8 },
                    { 815, "Kala | Balge", 8 },
                    { 816, "Konduga", 8 },
                    { 817, "Kukawa", 8 },
                    { 818, "Kwaya Kusar", 8 },
                    { 819, "Mafa", 8 },
                    { 820, "Magumeri", 8 },
                    { 821, "Maiduguri", 8 },
                    { 822, "Marte", 8 },
                    { 823, "Mobbar", 8 },
                    { 824, "Monguno", 8 },
                    { 825, "Ngala", 8 },
                    { 826, "Nganzai", 8 },
                    { 827, "Shani", 8 },
                    { 3029, "Surulere", 30 },
                    { 3028, "Ogo Oluwa", 30 },
                    { 3027, "Oluyole", 30 },
                    { 809, "Gubio", 8 },
                    { 2502, "Awe", 25 },
                    { 808, "Dikwa", 8 },
                    { 806, "Chibok", 8 },
                    { 714, "Obi", 7 },
                    { 715, "Ogbadibo", 7 },
                    { 716, "Ohimini", 7 },
                    { 717, "Oju", 7 },
                    { 718, "Okpokwu", 7 },
                    { 719, "Otukpo", 7 },
                    { 720, "Tarka", 7 },
                    { 721, "Ukum", 7 },
                    { 722, "Ushongo", 7 },
                    { 723, "Vandeikya", 7 },
                    { 3102, "Bassa", 31 },
                    { 3101, "Barkin Ladi", 31 },
                    { 3033, "Ona Ara", 30 },
                    { 3032, "Oyo East", 30 },
                    { 3031, "Ori Ire", 30 },
                    { 3030, "Orelope", 30 },
                    { 801, "Abadam", 8 },
                    { 802, "Askira | Uba", 8 },
                    { 803, "Bama", 8 },
                    { 804, "Bayo", 8 },
                    { 805, "Biu", 8 },
                    { 807, "Damboa", 8 },
                    { 2501, "Akwanga", 25 }
                });

            migrationBuilder.InsertData(
                table: "Courses",
                columns: new[] { "Id", "FacultyId", "Name" },
                values: new object[,]
                {
                    { 1, 1, "Animal Science" },
                    { 14, 11, "Microbiology" },
                    { 64, 6, "Social Work" },
                    { 17, 11, "Zoology" },
                    { 20, 4, "Business Administration" },
                    { 19, 4, "Marketing" },
                    { 18, 4, "Accountancy" },
                    { 39, 3, "Anaesthesia" },
                    { 49, 3, "Ophthalmology" },
                    { 40, 3, "Anatomy" },
                    { 63, 6, "Religious and Cultural Studies" },
                    { 62, 6, "Sociology & Anthropology" },
                    { 61, 6, "Geography" },
                    { 60, 6, "Economics" },
                    { 25, 5, "Adult Education" },
                    { 26, 5, "Education Foundation" },
                    { 50, 3, "Otolaringology" },
                    { 15, 11, "Biochemistry" },
                    { 58, 6, "Public Administration" },
                    { 27, 5, "Health & Physical Education" },
                    { 57, 6, "Philosophy" },
                    { 32, 5, "Vocational Teacher Education" },
                    { 31, 5, "Home Economics" },
                    { 48, 3, "Obstetrics & Gaenecology" },
                    { 47, 3, "Morbid Anatomy" },
                    { 30, 5, "Computer Education" },
                    { 29, 5, "Social Science Education" },
                    { 28, 5, "Library Sciences Education" },
                    { 46, 3, "Medical Microbiology" },
                    { 45, 3, "Medical Biochemistry" },
                    { 44, 3, "Haematology & Immunology" },
                    { 43, 3, "Dermatology" },
                    { 59, 6, "Psychology" },
                    { 51, 3, "Paediatrics" },
                    { 52, 3, "Paediatric Surgery" },
                    { 53, 3, "Pharmacology & Therapeutics" },
                    { 16, 11, "Plant Sciences" },
                    { 2, 1, "Soil Science" },
                    { 3, 1, "Agric. Economics" },
                    { 4, 1, "Agric. Extension" },
                    { 5, 2, "Mass Communication" },
                    { 6, 2, "Archaeology & Tourism" },
                    { 7, 2, "History & International Studies" },
                    { 38, 7, "Materials & Metallurgical Engineering" },
                    { 37, 7, "Agric. & Bioresources Engineering" },
                    { 36, 7, "Mechanical Engineering" },
                    { 35, 7, "Electrical Engineering" },
                    { 34, 7, "Electronic Engineering" },
                    { 33, 7, "Civil Engineering" },
                    { 42, 3, "Community Medicine" },
                    { 41, 3, "Chemical Pathology" },
                    { 9, 2, "Performing Arts" },
                    { 54, 3, "Physiological Medicine" },
                    { 55, 3, "Radiation Medicine" },
                    { 56, 3, "Surgery" },
                    { 21, 4, "Banking & Finance" },
                    { 22, 4, "Business Management" },
                    { 23, 5, "Arts Education" },
                    { 13, 2, "Linguistics & Nigerian Languages" },
                    { 24, 5, "Science Education" },
                    { 12, 2, "Foreign Languages" },
                    { 11, 2, "English & Literary Studies" },
                    { 10, 2, "Music" },
                    { 8, 2, "Fine & Applied Arts" }
                });

            migrationBuilder.InsertData(
                table: "Governors",
                columns: new[] { "Id", "EndsTenure", "Name", "StartsTenure", "StateId" },
                values: new object[,]
                {
                    { 114, "26-Nov-18", "Rauf Aregbesola", "26-Nov-10", 29 },
                    { 115, "Incumbent", "Adegboyega Oyetola", "26-Nov-18", 29 },
                    { 6, "29-Apr-08", "James Shaibu Barka", "26-Feb-08", 2 },
                    { 5, "26-Feb-08", "Murtala Nyako", "29-May-07", 2 },
                    { 4, "29-May-07", "Boni Haruna", "29-May-99", 2 },
                    { 47, "12-Nov-16", "Comrade Adams A. Oshiomhole", "12-Nov-08", 12 },
                    { 112, "29-May-03", "Adebisi Akande", "29-May-99", 29 },
                    { 57, "Till Date", "Dr. Kayode Fayemi", "16th Oct 2018", 13 },
                    { 56, "16th Oct 2018", "Ayo Fayose", "16th Oct 2014", 13 },
                    { 55, "16th Oct 2014", "Dr. Kayode Fayemi", "15th Oct 2010", 13 },
                    { 54, "15-Oct-10", "Segun Oni", "29-May-07", 13 },
                    { 53, "29-May-07", "Tope Ademiluyi", "27-Apr-07", 13 },
                    { 52, "27-Apr-07", "Tunji Olurin", "18-Oct-06", 13 },
                    { 51, "18-Oct-06", "Chief Friday Aderemi", "17-Oct-06", 13 },
                    { 113, "26-Nov-10", "Olagunsoye Oyinlola", "29-May-03", 29 },
                    { 50, "16-Oct-06", "Ayo Fayose", "29-May-03", 13 },
                    { 1, "29-May-07", "Orji Uzor Kalu", "29-May-99", 1 },
                    { 2, "29-May-15", "Theodore A. Orji", "29-May-07", 1 },
                    { 3, "Incumbent", "Okezie Ikpeazu", "29-May-15", 1 },
                    { 48, "Incumbent", "Godwin Obaseki", "12-Nov-16", 12 },
                    { 7, "15-Jul-14", "Murtala Nyako", "29-Apr-08", 2 },
                    { 46, "12-Nov-08", "Professor Oserheimen Osunbor", "29-May-07", 12 },
                    { 45, "29-May-07", "Chief Lucky Igbinedion", "29-May-99", 12 },
                    { 49, "29-May-03", "Otunba Niyi Adebayo", "29-May-99", 13 },
                    { 8, "1-Oct-14", "Alhaji Ahmadu�Umaru Fintiri", "15-Jul-14", 2 },
                    { 11, "29-May-07", "Victor Attah", "29-May-99", 3 },
                    { 10, "Incumbent", "Bindo Jibrilla", "29-May-15", 2 },
                    { 118, "7-Dec-06", "Christopher Alao-Akala", "12-Jan-06", 30 },
                    { 119, "11-May", "Christopher Alao-Akala", "29-May-07", 30 },
                    { 120, "Incumbent", "Abiola Ajimobi", "11-May", 30 },
                    { 19, "Incumbent", "Willie Obiano", "17-Mar-14", 4 },
                    { 31, "29-May-15", "Gabriel Suswam", "29-May-07", 7 },
                    { 30, "29-May-07", "George Akume", "29-May-99", 7 },
                    { 29, "Present", "Henry Dickson", "14-Feb-12", 6 },
                    { 28, "14-Feb-12", "Nestor Binabo", "27-Jan-12", 6 },
                    { 27, "27-Jan-12", "Timipre Sylva", "27-May-08", 6 },
                    { 26, "27-May-08", "Werinipre Seibarugo", "16-Apr-08", 6 },
                    { 25, "16-Apr-08", "Timipre Sylva", "29-May-07", 6 },
                    { 24, "29-May-07", "Goodluck Jonathan", "9-Dec-05", 6 },
                    { 23, "9-Dec-05", "Diepreye Alamieyeseigha", "29-May-99", 6 },
                    { 127, "Incumbent", "Simon Bako Lalong", "29-May-15", 31 },
                    { 126, "29-May-15", "Jonah David Jang", "29-May-07", 31 },
                    { 125, "29-May-07", "Joshua Dariye", "27-Apr-07", 31 },
                    { 22, "Incumbent", "Barrister M. A. ABUBAKAR", "29-May-15", 5 },
                    { 21, "29-May-20", "Malam Isa Yuguda", "29-May-07", 5 },
                    { 20, "29-May-07", "Ahmad Adamu Mu'azu", "29-May-99", 5 },
                    { 121, "18-May-04", "Joshua Dariye", "29-May-99", 31 },
                    { 122, "18-Nov-04", "Chris Alli", "18-May-04", 31 },
                    { 117, "28-May-07", "Rashidi Adewolu Ladoja", "29-May-03", 30 },
                    { 116, "28-May-03", "Dr.�Lam Adesina", "29-May-99", 30 },
                    { 32, "Incumbent", "Samuel Ortom", "29-May-15", 7 },
                    { 18, "17-Mar-14", "Peter Obi", "9-Feb-07", 4 },
                    { 131, "Incumbent", "Ezenwo Wike", "29-May-15", 32 },
                    { 130, "29-May-15", "Chibuike Amaechi", "26-Oct-07", 32 },
                    { 129, "26-Oct-07", "Celestine Omehia", "29-May-07", 32 },
                    { 128, "29-May-07", "Peter Odili", "29-May-99", 32 },
                    { 44, "Incumbent", "Dave Umahi", "29-May-15", 11 },
                    { 43, "29-May-15", "Martin Elechi", "29-May-07", 11 },
                    { 42, "29-May-07", "Sam Egwu", "29-May-99", 11 },
                    { 12, "29-May-15", "Godswill Akpabio", "29-May-07", 3 },
                    { 13, "Incumbent", "Udom Gabriel Emmanuel", "29-May-15", 3 },
                    { 41, "Incumbent", "Ifeanyi Okowa", "29-May-15", 10 },
                    { 9, "29-May-15", "Bala James Ngilari", "1-Oct-14", 2 },
                    { 40, "29-May-15", "Emmanuel Uduaghan", "29-May-07", 10 },
                    { 38, "Incumbent", "Benedict Ayade", "29-May-15", 9 },
                    { 37, "29-May-15", "Liyel Imoke", "29-May-07", 9 },
                    { 36, "29-May-07", "Donald Duke", "29-May-99", 9 },
                    { 14, "29-May-03", "Chinwoke Mbadinuju", "29-May-99", 4 },
                    { 15, "17-Mar-06", "Chris Ngige", "29-May-03", 4 },
                    { 35, "Incumbent", "Kashim Shettima", "29-May-11", 8 },
                    { 34, "29-May-11", "Ali Modu Sheriff", "29-May-03", 8 },
                    { 33, "29-May-03", "Mala Kachalla", "29-May-99", 8 },
                    { 16, "3-Nov-06", "Peter Obi", "17-Mar-06", 4 },
                    { 17, "9-Feb-07", "Virginia Etiaba", "3-Nov-06", 4 },
                    { 39, "29-May-07", "James Ibori", "29-May-99", 10 },
                    { 109, "2009-02", "Olusegun Agagu", "2003-05", 28 },
                    { 124, "27-Apr-07", "Michael Botmang", "13-Nov-06", 31 },
                    { 59, "29-May-15", "Sullivan Chime", "29-May-07", 14 },
                    { 84, "2-Apr-12", "Aminu Musa Habib Jega", "24-Feb-12", 21 },
                    { 83, "24-Feb-12", "Usman Saidu Nasamu Dakingari", "29-May-07", 21 },
                    { 82, "29-May-07", "Adamu Aliero", "29-May-99", 21 },
                    { 144, "present", "Ibrahim Gaidam", "2009", 35 },
                    { 143, "27-Jan-09", "Mamman Bello Ali", "29-May-07", 35 },
                    { 81, "Incumbent", "Aminu Bello Masari", "29-May-15", 20 },
                    { 80, "29-May-15", "Ibrahim Shema", "29-May-07", 20 },
                    { 79, "29-May-07", "Umaru Musa Yar'Adua", "29-May-99", 20 },
                    { 58, "29-May-07", "Chimaroke Nnamani", "29-May-99", 14 },
                    { 102, "29-May-07", "Abdulkadir Kure", "29-May-99", 26 },
                    { 103, "29-May-15", "Mu'azu Babangida Aliyu", "29-May-07", 26 },
                    { 104, "-", "Abubakar Sani Bello", "29-May-15", 26 },
                    { 78, "incumbent", "Abdullahi Umar Ganduje", "15-May", 19 },
                    { 77, "15-May", "Engineer (Dr.) Rabiu Musa Kwankwaso", "11-May", 19 },
                    { 76, "11-May", "Malam�Ibrahim Shekarau", "3-May", 19 },
                    { 85, "29-May-15", "Usman Saidu Nasamu Dakingari", "2-Apr-12", 21 },
                    { 86, "Incumbent", "Abubakar Atiku Bagudu", "29-May-15", 21 },
                    { 87, "29-May-03", "Abubakar Audu", "29-May-99", 22 },
                    { 88, "6-Feb-08", "Ibrahim Idris", "29-May-03", 22 },
                    { 147, "incumbent", "Abdul'aziz Abubakar Yari", "11-May", 36 },
                    { 146, "11-May", "Mahmud Shinkafi", "29-May-07", 36 },
                    { 145, "29-May-07", "Ahmad Sani Yarima", "29-May-99", 36 },
                    { 98, "", "Mr Akinwunmi Ambode", "29-May-15", 24 },
                    { 97, "29-May-15", "Mr Babatunde Fashola", "29-May-07", 24 },
                    { 96, "29-May-07", "Mr Bola Tinubu", "29-May-99", 24 },
                    { 95, "Incumbent", "Abdulfatah Ahmed", "29-May-11", 23 },
                    { 75, "3-May", "Engineer (Dr.)�Rabiu Musa Kwankwaso", "May-99", 19 },
                    { 94, "29-May-11", "Bukola Saraki", "29-May-03", 23 },
                    { 99, "29-May-07", "Abdullahi Adamu", "29-May-99", 25 },
                    { 100, "11-May", "Aliyu Doma", "29-May-07", 25 },
                    { 101, "", "Umaru Tanko Al-Makura", "11-May", 25 },
                    { 92, "Incumbent", "Alhaji Yahaya Adoza Bello", "27-Jan-16", 22 },
                    { 91, "", "Idris Wada", "12-Jan", 22 },
                    { 90, "11-Jan", "Ibrahim Idris", "29-Mar-08", 22 },
                    { 89, "29-Mar-08", "Clarence Olafemi", "6-Feb-08", 22 },
                    { 93, "29-May-03", "Mohammed Lawal", "29-May-99", 23 },
                    { 74, "Incumbent", "Nasiru Ahmed El-Rufai", "29-May-15", 18 },
                    { 142, "29-May-07", "Bukar Abba Ibrahim", "29-May-99", 35 },
                    { 72, "15-Dec-12", "Patrick Ibrahim Yakowa", "20-May-10", 18 },
                    { 70, "29-May-07", "Ahmed Makarfi", "29-May-99", 18 },
                    { 69, "Incumbent", "Badaru Abubakar", "29-May-15", 17 },
                    { 68, "29-May-15", "Sule Lamido", "29-May-07", 17 },
                    { 67, "29-May-07", "Ibrahim Saminu Turaki", "29-May-99", 17 },
                    { 66, "Incumbent", "Owelle Rochas Anayo Okorocha", "29-May-11", 16 },
                    { 73, "29-May-15", "Mukhtar Ramalan Yero", "15-Dec-12", 18 },
                    { 64, "29-May-07", "Achike Udenwa", "29-May-99", 16 },
                    { 63, "Incumbent", "Ibrahim Hassan Dankwambo", "11-May", 15 },
                    { 62, "11-May", "Mohammed Danjuma Goje", "29-May-03", 15 },
                    { 137, "29-May-07", "Jolly Nyame", "29-May-99", 34 },
                    { 61, "29-May-03", "Abubakar Habu Hashidu", "29-May-99", 15 },
                    { 108, "2003-05", "Adebayo Adefarati", "1999-05", 28 },
                    { 123, "13-Nov-06", "Joshua Dariye", "18-Nov-04", 31 },
                    { 110, "2017-02", "Olusegun Mimiko", "2009-02", 28 },
                    { 111, "Incumbent", "Oluwarotimi Odunayo Akeredolu", "2017-02", 28 },
                    { 135, "29-May-15", "Aliyu Magatakarda Wamakko", "29-May-08", 33 },
                    { 134, "29-May-08", "Abdullahi Balarabe Salame", "11-Apr-08", 33 },
                    { 133, "11-Apr-08", "Aliyu Magatakarda Wamakko", "29-May-07", 33 },
                    { 132, "29-May-07", "Attahiru Bafarawa", "29-May-99", 33 },
                    { 60, "Incumbent", "Ifeanyi Ugwuanyi", "29-May-15", 14 },
                    { 136, "Incumbent", "Aminu Waziri Tambuwal", "28-May-15", 33 },
                    { 138, "12-Oct", "Danbaba Danfulani Suntai", "29-May-07", 34 },
                    { 65, "29-May-11", "Ikedi G. Ohakim", "29-May-07", 16 },
                    { 140, "29-May-15", "Abubakar sani danladi", "2013", 34 },
                    { 105, "29-May-03", "Olusegun Osoba", "29-May-99", 27 },
                    { 71, "19-May-10", "Mohammed Namadi Sambo", "29-May-07", 18 },
                    { 107, "Incumbent", "Ibikunle Amosun", "29-May-11", 27 },
                    { 106, "11-May", "Gbenga Daniel", "29-May-03", 27 },
                    { 139, "2013", "Garba Umar", "12-Oct", 34 },
                    { 141, "Incumbent", "Darius Dickson Ishaku", "29-May-15", 34 }
                });

            migrationBuilder.InsertData(
                table: "Schools",
                columns: new[] { "Id", "Abbreviation", "Name", "SchoolCategoryId", "StateId" },
                values: new object[,]
                {
                    { 62, "", "Taraba State University", 3, 34 },
                    { 168, "", "Federal College of Animal Health and Production Technology, Vom", 2, 31 },
                    { 60, "", "Universoty of Jos", 3, 31 },
                    { 64, "VUNA", "Veritas University (Catholic University of Nigeria) Abuja", 3, 37 },
                    { 176, "", "Rivers State Polytechnic", 2, 32 },
                    { 175, "", "Port Harcourt Polytechnic", 2, 32 },
                    { 180, "", "Abdul Gusau Polytechnic", 2, 36 },
                    { 182, "", "Abdul Gusau Polytechnic", 2, 36 },
                    { 174, "", "Eastern Polytechnic", 2, 32 },
                    { 181, "", "Federal Polytechnic, Namoda", 2, 36 },
                    { 177, "", "College of Agriculture, Jalingo", 2, 34 },
                    { 68, "", "Adamawa State Polytechnic", 2, 2 },
                    { 4, "ADSU", "Adamawa State University", 3, 2 },
                    { 3, "AUN", "American University of Nigeria", 3, 2 },
                    { 69, "", "Federal Polytechnic, Mubi", 2, 2 },
                    { 61, "UNIPORT", "University of Port Harcourt", 3, 32 },
                    { 170, "", "Federal College of Forestry. Jos", 2, 31 },
                    { 171, "", "Federal College of Land Resources Technology, Kuru", 2, 31 },
                    { 63, "YSU", "Bukar Abba Ibrahim University", 3, 35 },
                    { 74, "", "Maritime Academy of Nigeria", 2, 3 },
                    { 73, "", "Heritage Polytechnic", 2, 3 },
                    { 72, "", "Foundation College of Technology", 2, 3 },
                    { 71, "", "Akwa-Ibom College of Agriculture", 2, 3 },
                    { 70, "", "Akwa Ibom State Polytechnic", 2, 3 },
                    { 178, "", "Federal Polytechnic, Damaturu", 2, 35 },
                    { 179, "", "Mai Idris Alooma Polytechnic", 2, 35 },
                    { 169, "", "Federal College of Education, Pankshin", 2, 31 },
                    { 5, "AKSU", "Akwa Ibom State University", 3, 3 },
                    { 2, "", "Gregory University", 3, 1 },
                    { 1, "ABSU", "Abia State University", 3, 1 },
                    { 6, "ANSU", "Anambra State University", 3, 4 },
                    { 75, "", "Ekwenugo Okeke Polytechnic", 2, 4 },
                    { 76, "", "Federal Polytechnic, Oko", 2, 4 },
                    { 77, "", "The UA College of Science and Technology , Isuofia", 2, 4 },
                    { 173, "", "Plateau State Polytechnic", 2, 31 },
                    { 172, "", "Plateau State College of Agriculture", 2, 31 },
                    { 103, "", "Temple Gate Polytechnic", 2, 1 },
                    { 34, "CU", "City University", 3, 24 },
                    { 88, "", "Divine Polytechnic, Mkpani", 2, 9 },
                    { 78, "", "Abubakar Tafari Ali Polytechnic", 2, 5 },
                    { 108, "", "College of Agriculture and Animal Science", 2, 18 },
                    { 109, "", "Federal College of Chemical and Leather and Technology", 2, 18 },
                    { 110, "", "Federal College of Forestry Mechanisation", 2, 18 },
                    { 111, "", "Kaduna Polytechnic", 2, 18 },
                    { 112, "", "Nigerian College of Aviation Technology", 2, 18 },
                    { 113, "", "federal school of statistics Manchok", 2, 18 },
                    { 25, "CUT", "City University of Technology", 3, 18 },
                    { 114, "", "Nuhu Bamalli Polytechnic", 2, 18 },
                    { 65, "NTNU", "Nigerian Turkish Nile University", 3, 37 },
                    { 26, "BUK", "Bayero University", 3, 19 },
                    { 145, "", "Niger State Polytechnic", 2, 26 },
                    { 144, "", "Niger State College of Agriculture", 2, 26 },
                    { 143, "", "Federal Polytechnic, Bida", 2, 26 },
                    { 142, "", "Federal College of Wildlife Management", 2, 26 },
                    { 115, "", "Samaru College of Agriculture", 2, 18 },
                    { 141, "", "Federal College of Fresh Water Fisheries Technology", 2, 26 },
                    { 24, "ABU", "Ahmadu Bello University", 3, 18 },
                    { 40, "BU", "Babcock University", 3, 27 },
                    { 106, "", "Hussaini Adamu Federal Polytechnic", 2, 17 },
                    { 107, "", "Hussani Adamu Polytechnic", 2, 17 },
                    { 152, "", "Ogun State College of Health Technology", 2, 27 },
                    { 151, "", "Moshood Abiola Polytechnic", 2, 27 },
                    { 150, "", "Marvic Polytechnic", 2, 27 },
                    { 149, "", "Gateway Polytechnic Saapade", 2, 27 },
                    { 39, "FUNAAB", "Federal University of Agriculture, Abeokuta", 3, 27 },
                    { 148, "", "Federal Polytechnic, Ilaro", 2, 27 },
                    { 146, "", "Abraham Adesanya Polytechnic", 2, 27 },
                    { 45, "OOU", "Olabisi Onabanjo University", 3, 27 },
                    { 44, "CU", "Crescent University", 3, 27 },
                    { 43, "CU", "Crawford University", 3, 27 },
                    { 42, "CU", "Covenant University", 3, 27 },
                    { 41, "BUT", "Bells University of Technology", 3, 27 },
                    { 147, "", "Allover Central Polytechnic", 2, 27 },
                    { 105, "", "Imo State Technological Skills Acquisition Center", 2, 16 },
                    { 116, "", "Audu Bako School of Agriculture", 2, 19 },
                    { 118, "", "Mohammed Abdullahi Wase Polytechnic", 2, 19 },
                    { 127, "", "Kwara State Polytechnic", 2, 23 },
                    { 32, "CU", "CETEP City University", 3, 24 },
                    { 136, "", "Yaba College of Technology", 2, 24 },
                    { 135, "", "Wolex Polytechnic", 2, 24 },
                    { 134, "", "Wavecrest College of Hospitality", 2, 24 },
                    { 133, "", "School of Agriculture, Ikorodu", 2, 24 },
                    { 126, "", "Federal Polytechnic, Offa", 2, 23 },
                    { 132, "", "Ronik Polytechnic", 2, 24 },
                    { 130, "", "Lagos City Polytechnic", 2, 24 },
                    { 129, "", "Grace Polytechnic", 2, 24 },
                    { 128, "", "Federal College of Fisheries and Marine Technology", 2, 24 },
                    { 37, "UNILAG", "University of Lagos", 3, 24 },
                    { 36, "LASU", "Lagos State University", 3, 24 },
                    { 35, "NOUN", "National Open University of Nigeria", 3, 24 },
                    { 131, "", "Lagos State Polytechnic", 2, 24 },
                    { 117, "", "Kano State Polytechnic", 2, 19 },
                    { 31, "LU", "Landmark University", 3, 23 },
                    { 29, "AHU", "Al-Hikmah University", 3, 23 },
                    { 27, "FUDM", "Federal University, Dutsin-Ma", 3, 20 },
                    { 28, "UMYU", "Umaru Musa Yar'adua University Katsina", 3, 20 },
                    { 119, "", "Hassan Usman Katsina Polytechnic", 2, 20 },
                    { 120, "", "College of Agriculture, Zuru", 2, 21 },
                    { 121, "", "Federal Polytechnic, Birnin-Kebbi", 2, 21 },
                    { 122, "", "Kebbi State Polytechnic", 2, 21 },
                    { 30, "", "University of Ilorin", 3, 23 },
                    { 123, "", "College of Agriculture, Kabba", 2, 22 },
                    { 140, "", "Nasarawa State Polytechnic", 2, 25 },
                    { 139, "", "Federal Polytechnic, Nassarawa", 2, 25 },
                    { 138, "", "Maurid Institute of Management & Technology, Nasarawa", 2, 25 },
                    { 137, "", "College of Agriculture, Lafia", 2, 25 },
                    { 38, "BU", "ECWA Bingham University", 3, 25 },
                    { 125, "", "Kogi State Polytechnic", 2, 22 },
                    { 124, "", "Federal Polytechnic, Idah", 2, 22 },
                    { 7, "ATBU", "Abubakar Tafawa Balewa University", 3, 5 },
                    { 104, "", "Imo State Polytechnic", 2, 16 },
                    { 101, "", "Federal College of Land Resources Technology, Owerri", 2, 16 },
                    { 9, "CRUTECH", "Cross River University of Technology", 3, 9 },
                    { 10, "UNICAL", "University of Calabar", 3, 9 },
                    { 86, "", "Ibrahim Babangida College of Agriculture", 2, 9 },
                    { 87, "", "The Polytechnic, Calabar", 2, 9 },
                    { 33, "CUl", "Caleb University", 3, 24 },
                    { 89, "", "Delta State College of Agriculture", 2, 9 },
                    { 85, "", "Ramat Polytechnic", 2, 8 },
                    { 11, "DELSU", "Delta State University, Abraka", 3, 10 },
                    { 90, "", "Delta State Polytechnic�(three institutions)", 2, 10 },
                    { 91, "", "Petroleum Training Institute", 2, 10 },
                    { 13, "EBSU", "Ebonyi State University", 3, 11 },
                    { 14, "EUA", "Evangel University, Akaeze", 3, 11 },
                    { 66, "FUNAI", "Federal University Ndufe Alike, Ikwo", 3, 11 },
                    { 92, "", "Akanu Ibiam Federal Polytechnic", 2, 11 },
                    { 12, "MCIU", "Michael and Cecilia Ibru University", 3, 10 },
                    { 93, "", "Federal College of Agriculture, Ishiagu", 2, 11 },
                    { 84, "", "Borno College of Agriculture", 2, 8 },
                    { 82, "", "Benue State Polytechnic", 2, 7 },
                    { 79, "", "Federal Polytechnic, Bauchi", 2, 5 },
                    { 80, "", "Bayelsa State College of Arts and Science", 2, 6 },
                    { 81, "", "Federal Polytechnic Ekowe Bayelsa State", 2, 6 },
                    { 167, "", "The Oke-Ogun Polytechnic, Saki", 2, 30 },
                    { 166, "", "Tower Polytechnic, Ibadan", 2, 30 },
                    { 165, "", "The Kings Poly, Shaki, Oyo", 2, 30 },
                    { 83, "", "Akperan Orshi College of Agriculture", 2, 7 },
                    { 164, "", "The Polytechnic, Ibadan", 2, 30 },
                    { 162, "", "Federal College of Animal Health and Production Technology, Ibadan", 2, 30 },
                    { 161, "", "Federal College of Animal Health & Production Technology", 2, 30 },
                    { 59, "UI", "University of Ibadan", 3, 30 },
                    { 58, "KU", "Koladaisi University", 3, 30 },
                    { 57, "ACU", "Ajayi Crowther University", 3, 30 },
                    { 8, "BSU", "Benue State University", 3, 7 },
                    { 163, "", "Federal College of Forestry, Ibadan", 2, 30 },
                    { 102, "", "Federal Polytechnic, Nekede", 2, 16 },
                    { 160, "", "Southern Nigeria Institute of Innovative Technology (SNIITPOLY)", 2, 29 },
                    { 158, "", "Polytechnic Ile-Ife", 2, 29 },
                    { 20, "CU", "Crawford University", 3, 13 },
                    { 97, "", "Federal Polytechnic, Ado-Ekiti", 2, 13 },
                    { 21, "CU", "Caritas University", 3, 14 },
                    { 22, "GOU", "Godfrey Okoye University", 3, 14 },
                    { 23, "UNN", "University of Nigeria, Nsukka", 3, 14 },
                    { 98, "", "Federal School of Dental Technology & Therapy", 2, 14 },
                    { 19, "ABUAD", "Afe Babalola University", 3, 13 },
                    { 153, "", "Rufus Giwa Polytechnic", 2, 28 },
                    { 49, "", "Elizade University", 3, 28 },
                    { 48, "AC", "Achievers University", 3, 28 },
                    { 47, "AAUA", "Adekunle Ajasin University", 3, 28 },
                    { 46, "AAUA", "Adekunle Ajasin University", 3, 28 },
                    { 99, "", "Institute of Management Technology, Enugu", 2, 14 },
                    { 100, "", "Our Saviour Institute of Science and Technology", 2, 14 },
                    { 50, "FUTA", "Federal University of Technology Akure", 3, 28 },
                    { 159, "", "Interlink Polytechnic", 2, 29 },
                    { 96, "", "Shaka Polytechnic", 2, 12 },
                    { 94, "", "Auchi Polytechnic", 2, 12 },
                    { 157, "", "Igbajo Polytechnic, Igbajo", 2, 29 },
                    { 156, "", "Osun State Polytechnic", 2, 29 },
                    { 155, "", "Osun State College of Technology", 2, 29 },
                    { 154, "", "Federal Polytechnic, Ede", 2, 29 },
                    { 56, "OAU", "Obafemi Awolowo University", 3, 29 },
                    { 55, "OUI", "Oduduwa University", 3, 29 },
                    { 95, "", "Kings Polytechnic", 2, 12 },
                    { 54, "FUO", "Fountain University, Osogbo", 3, 29 },
                    { 52, "RUN", "Redeemer's University Nigeria", 3, 29 },
                    { 51, "JABU", "Joseph Ayo Babalola University", 3, 29 },
                    { 15, "AAU", "Ambrose Alli University", 3, 12 },
                    { 16, "BIU", "Benson Idahosa University", 3, 12 },
                    { 17, "IUO", "Igbinedion University", 3, 12 },
                    { 18, "UNIBEN", "University of Benin", 3, 12 },
                    { 53, "BU", "Bowen University", 3, 29 },
                    { 67, "", "Dorben Polytechnic", 2, 37 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Cities_StateId",
                table: "Cities",
                column: "StateId");

            migrationBuilder.CreateIndex(
                name: "IX_Courses_FacultyId",
                table: "Courses",
                column: "FacultyId");

            migrationBuilder.CreateIndex(
                name: "IX_Faculties_SchoolId",
                table: "Faculties",
                column: "SchoolId");

            migrationBuilder.CreateIndex(
                name: "IX_Governors_StateId",
                table: "Governors",
                column: "StateId");

            migrationBuilder.CreateIndex(
                name: "IX_Schools_SchoolCategoryId",
                table: "Schools",
                column: "SchoolCategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_Schools_StateId",
                table: "Schools",
                column: "StateId");

            migrationBuilder.CreateIndex(
                name: "IX_Students_CourseId",
                table: "Students",
                column: "CourseId");

            migrationBuilder.CreateIndex(
                name: "IX_Students_StateId",
                table: "Students",
                column: "StateId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Cities");

            migrationBuilder.DropTable(
                name: "Governors");

            migrationBuilder.DropTable(
                name: "Students");

            migrationBuilder.DropTable(
                name: "Courses");

            migrationBuilder.DropTable(
                name: "Faculties");

            migrationBuilder.DropTable(
                name: "Schools");

            migrationBuilder.DropTable(
                name: "SchoolCategories");

            migrationBuilder.DropTable(
                name: "States");
        }
    }
}
